### ISSUE TITLE
Exception happened when I tried to apply LDA Topic Modeling on a file containing 20 documents

### ISSUE THREAD

**Issue by FanYang525** [ckling/promoss#2]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArithmeticException: / by zero
	at org.gesis.promoss.tools.text.Corpus.readDocs(Corpus.java:309)
	at org.gesis.promoss.inference.LDA_CSVB.initialise(LDA_CSVB.java:144)
	at org.gesis.promoss.inference.Run.main(Run.java:446)
	... 5 more

**Comment by ckling** [comment]
Hi,
thanks, the code actually did not work for very small files (<50 documents).
Sorry for the late reply, I somehow missed the notification mail.
I fixed it!
Cheers
Christoph
